export type PrayerLocation = {
  country: string;
  city: string;
  countryAr: string;
  cityAr: string;
  latitude: number;
  longitude: number;
  timeZone: string;
};

export const prayerLocations: PrayerLocation[] = [
  { country: "Egypt", city: "Cairo", countryAr: "مصر", cityAr: "القاهرة", latitude: 30.0444, longitude: 31.2357, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Alexandria", countryAr: "مصر", cityAr: "الإسكندرية", latitude: 31.2001, longitude: 29.9187, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Giza", countryAr: "مصر", cityAr: "الجيزة", latitude: 30.0131, longitude: 31.2089, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Mansoura", countryAr: "مصر", cityAr: "المنصورة", latitude: 31.0409, longitude: 31.3785, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Tanta", countryAr: "مصر", cityAr: "طنطا", latitude: 30.7865, longitude: 31.0004, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Damanhur", countryAr: "مصر", cityAr: "دمنهور", latitude: 31.0341, longitude: 30.4682, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Asyut", countryAr: "مصر", cityAr: "أسيوط", latitude: 27.1809, longitude: 31.1837, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Aswan", countryAr: "مصر", cityAr: "أسوان", latitude: 24.0889, longitude: 32.8998, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Luxor", countryAr: "مصر", cityAr: "الأقصر", latitude: 25.6872, longitude: 32.6396, timeZone: "Africa/Cairo" },
  { country: "Egypt", city: "Port Said", countryAr: "مصر", cityAr: "بورسعيد", latitude: 31.2653, longitude: 32.3019, timeZone: "Africa/Cairo" },
  { country: "Saudi Arabia", city: "Riyadh", countryAr: "السعودية", cityAr: "الرياض", latitude: 24.7136, longitude: 46.6753, timeZone: "Asia/Riyadh" },
  { country: "Saudi Arabia", city: "Jeddah", countryAr: "السعودية", cityAr: "جدة", latitude: 21.4858, longitude: 39.1925, timeZone: "Asia/Riyadh" },
  { country: "Saudi Arabia", city: "Mecca", countryAr: "السعودية", cityAr: "مكة", latitude: 21.3891, longitude: 39.8579, timeZone: "Asia/Riyadh" },
  { country: "Saudi Arabia", city: "Medina", countryAr: "السعودية", cityAr: "المدينة", latitude: 24.5247, longitude: 39.5692, timeZone: "Asia/Riyadh" },
  { country: "Saudi Arabia", city: "Dammam", countryAr: "السعودية", cityAr: "الدمام", latitude: 26.4207, longitude: 50.0888, timeZone: "Asia/Riyadh" },
  { country: "Saudi Arabia", city: "Tabuk", countryAr: "السعودية", cityAr: "تبوك", latitude: 28.3838, longitude: 36.5662, timeZone: "Asia/Riyadh" },
  { country: "United Arab Emirates", city: "Dubai", countryAr: "الإمارات", cityAr: "دبي", latitude: 25.2048, longitude: 55.2708, timeZone: "Asia/Dubai" },
  { country: "United Arab Emirates", city: "Abu Dhabi", countryAr: "الإمارات", cityAr: "أبوظبي", latitude: 24.4539, longitude: 54.3773, timeZone: "Asia/Dubai" },
  { country: "United Arab Emirates", city: "Sharjah", countryAr: "الإمارات", cityAr: "الشارقة", latitude: 25.3463, longitude: 55.4209, timeZone: "Asia/Dubai" },
  { country: "United Arab Emirates", city: "Ajman", countryAr: "الإمارات", cityAr: "عجمان", latitude: 25.4052, longitude: 55.5136, timeZone: "Asia/Dubai" },
  { country: "Kuwait", city: "Kuwait City", countryAr: "الكويت", cityAr: "مدينة الكويت", latitude: 29.3759, longitude: 47.9774, timeZone: "Asia/Kuwait" },
  { country: "Kuwait", city: "Hawalli", countryAr: "الكويت", cityAr: "حولي", latitude: 29.3375, longitude: 48.0287, timeZone: "Asia/Kuwait" },
  { country: "Qatar", city: "Doha", countryAr: "قطر", cityAr: "الدوحة", latitude: 25.2854, longitude: 51.5310, timeZone: "Asia/Qatar" },
  { country: "Qatar", city: "Al Rayyan", countryAr: "قطر", cityAr: "الريان", latitude: 25.2919, longitude: 51.4244, timeZone: "Asia/Qatar" },
  { country: "Bahrain", city: "Manama", countryAr: "البحرين", cityAr: "المنامة", latitude: 26.2235, longitude: 50.5876, timeZone: "Asia/Bahrain" },
  { country: "Bahrain", city: "Muharraq", countryAr: "البحرين", cityAr: "المحرق", latitude: 26.2572, longitude: 50.6119, timeZone: "Asia/Bahrain" },
  { country: "Oman", city: "Muscat", countryAr: "عُمان", cityAr: "مسقط", latitude: 23.5880, longitude: 58.3829, timeZone: "Asia/Muscat" },
  { country: "Oman", city: "Salalah", countryAr: "عُمان", cityAr: "صلالة", latitude: 17.0194, longitude: 54.1108, timeZone: "Asia/Muscat" },
  { country: "Jordan", city: "Amman", countryAr: "الأردن", cityAr: "عمّان", latitude: 31.9539, longitude: 35.9106, timeZone: "Asia/Amman" },
  { country: "Jordan", city: "Irbid", countryAr: "الأردن", cityAr: "إربد", latitude: 32.5556, longitude: 35.8500, timeZone: "Asia/Amman" },
  { country: "Jordan", city: "Zarqa", countryAr: "الأردن", cityAr: "الزرقاء", latitude: 32.0608, longitude: 36.0942, timeZone: "Asia/Amman" },
  { country: "Palestine", city: "Jerusalem", countryAr: "فلسطين", cityAr: "القدس", latitude: 31.7683, longitude: 35.2137, timeZone: "Asia/Jerusalem" },
  { country: "Palestine", city: "Gaza", countryAr: "فلسطين", cityAr: "غزة", latitude: 31.5017, longitude: 34.4668, timeZone: "Asia/Gaza" },
  { country: "Palestine", city: "Ramallah", countryAr: "فلسطين", cityAr: "رام الله", latitude: 31.9038, longitude: 35.2034, timeZone: "Asia/Jerusalem" },
  { country: "Lebanon", city: "Beirut", countryAr: "لبنان", cityAr: "بيروت", latitude: 33.8938, longitude: 35.5018, timeZone: "Asia/Beirut" },
  { country: "Lebanon", city: "Tripoli", countryAr: "لبنان", cityAr: "طرابلس", latitude: 34.4367, longitude: 35.8497, timeZone: "Asia/Beirut" },
  { country: "Syria", city: "Damascus", countryAr: "سوريا", cityAr: "دمشق", latitude: 33.5138, longitude: 36.2765, timeZone: "Asia/Damascus" },
  { country: "Syria", city: "Aleppo", countryAr: "سوريا", cityAr: "حلب", latitude: 36.2021, longitude: 37.1343, timeZone: "Asia/Damascus" },
  { country: "Syria", city: "Homs", countryAr: "سوريا", cityAr: "حمص", latitude: 34.7324, longitude: 36.7137, timeZone: "Asia/Damascus" },
  { country: "Iraq", city: "Baghdad", countryAr: "العراق", cityAr: "بغداد", latitude: 33.3152, longitude: 44.3661, timeZone: "Asia/Baghdad" },
  { country: "Iraq", city: "Basra", countryAr: "العراق", cityAr: "البصرة", latitude: 30.5085, longitude: 47.7804, timeZone: "Asia/Baghdad" },
  { country: "Iraq", city: "Mosul", countryAr: "العراق", cityAr: "الموصل", latitude: 36.3489, longitude: 43.1577, timeZone: "Asia/Baghdad" },
  { country: "Morocco", city: "Rabat", countryAr: "المغرب", cityAr: "الرباط", latitude: 34.0209, longitude: -6.8416, timeZone: "Africa/Casablanca" },
  { country: "Morocco", city: "Casablanca", countryAr: "المغرب", cityAr: "الدار البيضاء", latitude: 33.5731, longitude: -7.5898, timeZone: "Africa/Casablanca" },
  { country: "Morocco", city: "Marrakesh", countryAr: "المغرب", cityAr: "مراكش", latitude: 31.6295, longitude: -7.9811, timeZone: "Africa/Casablanca" },
  { country: "Algeria", city: "Algiers", countryAr: "الجزائر", cityAr: "الجزائر", latitude: 36.7538, longitude: 3.0588, timeZone: "Africa/Algiers" },
  { country: "Algeria", city: "Oran", countryAr: "الجزائر", cityAr: "وهران", latitude: 35.6971, longitude: -0.6308, timeZone: "Africa/Algiers" },
  { country: "Algeria", city: "Constantine", countryAr: "الجزائر", cityAr: "قسنطينة", latitude: 36.3650, longitude: 6.6147, timeZone: "Africa/Algiers" },
  { country: "Tunisia", city: "Tunis", countryAr: "تونس", cityAr: "تونس", latitude: 36.8065, longitude: 10.1815, timeZone: "Africa/Tunis" },
  { country: "Tunisia", city: "Sfax", countryAr: "تونس", cityAr: "صفاقس", latitude: 34.7406, longitude: 10.7603, timeZone: "Africa/Tunis" },
  { country: "Tunisia", city: "Sousse", countryAr: "تونس", cityAr: "سوسة", latitude: 35.8256, longitude: 10.63699, timeZone: "Africa/Tunis" },
  { country: "Libya", city: "Tripoli", countryAr: "ليبيا", cityAr: "طرابلس", latitude: 32.8872, longitude: 13.1913, timeZone: "Africa/Tripoli" },
  { country: "Libya", city: "Benghazi", countryAr: "ليبيا", cityAr: "بنغازي", latitude: 32.1194, longitude: 20.0868, timeZone: "Africa/Tripoli" },
  { country: "Sudan", city: "Khartoum", countryAr: "السودان", cityAr: "الخرطوم", latitude: 15.5007, longitude: 32.5599, timeZone: "Africa/Khartoum" },
  { country: "Sudan", city: "Omdurman", countryAr: "السودان", cityAr: "أم درمان", latitude: 15.6445, longitude: 32.4777, timeZone: "Africa/Khartoum" },
  { country: "Turkey", city: "Istanbul", countryAr: "تركيا", cityAr: "إسطنبول", latitude: 41.0082, longitude: 28.9784, timeZone: "Europe/Istanbul" },
  { country: "Turkey", city: "Ankara", countryAr: "تركيا", cityAr: "أنقرة", latitude: 39.9334, longitude: 32.8597, timeZone: "Europe/Istanbul" },
  { country: "Turkey", city: "Izmir", countryAr: "تركيا", cityAr: "إزمير", latitude: 38.4237, longitude: 27.1428, timeZone: "Europe/Istanbul" },
  { country: "United States", city: "New York", countryAr: "أمريكا", cityAr: "نيويورك", latitude: 40.7128, longitude: -74.0060, timeZone: "America/New_York" },
  { country: "United States", city: "Los Angeles", countryAr: "أمريكا", cityAr: "لوس أنجلوس", latitude: 34.0522, longitude: -118.2437, timeZone: "America/Los_Angeles" },
  { country: "United States", city: "Chicago", countryAr: "أمريكا", cityAr: "شيكاغو", latitude: 41.8781, longitude: -87.6298, timeZone: "America/Chicago" },
  { country: "United States", city: "Houston", countryAr: "أمريكا", cityAr: "هيوستن", latitude: 29.7604, longitude: -95.3698, timeZone: "America/Chicago" },
  { country: "United Kingdom", city: "London", countryAr: "بريطانيا", cityAr: "لندن", latitude: 51.5072, longitude: -0.1276, timeZone: "Europe/London" },
  { country: "United Kingdom", city: "Manchester", countryAr: "بريطانيا", cityAr: "مانشستر", latitude: 53.4808, longitude: -2.2426, timeZone: "Europe/London" },
  { country: "United Kingdom", city: "Birmingham", countryAr: "بريطانيا", cityAr: "برمنغهام", latitude: 52.4862, longitude: -1.8904, timeZone: "Europe/London" },
  { country: "France", city: "Paris", countryAr: "فرنسا", cityAr: "باريس", latitude: 48.8566, longitude: 2.3522, timeZone: "Europe/Paris" },
  { country: "France", city: "Marseille", countryAr: "فرنسا", cityAr: "مارسيليا", latitude: 43.2965, longitude: 5.3698, timeZone: "Europe/Paris" },
  { country: "France", city: "Lyon", countryAr: "فرنسا", cityAr: "ليون", latitude: 45.7640, longitude: 4.8357, timeZone: "Europe/Paris" },
  { country: "Germany", city: "Berlin", countryAr: "ألمانيا", cityAr: "برلين", latitude: 52.5200, longitude: 13.4050, timeZone: "Europe/Berlin" },
  { country: "Germany", city: "Munich", countryAr: "ألمانيا", cityAr: "ميونخ", latitude: 48.1351, longitude: 11.5820, timeZone: "Europe/Berlin" },
  { country: "Germany", city: "Frankfurt", countryAr: "ألمانيا", cityAr: "فرانكفورت", latitude: 50.1109, longitude: 8.6821, timeZone: "Europe/Berlin" },
  { country: "Canada", city: "Toronto", countryAr: "كندا", cityAr: "تورونتو", latitude: 43.6532, longitude: -79.3832, timeZone: "America/Toronto" },
  { country: "Canada", city: "Montreal", countryAr: "كندا", cityAr: "مونتريال", latitude: 45.5019, longitude: -73.5674, timeZone: "America/Toronto" },
  { country: "Canada", city: "Vancouver", countryAr: "كندا", cityAr: "فانكوفر", latitude: 49.2827, longitude: -123.1207, timeZone: "America/Vancouver" },
  { country: "Australia", city: "Sydney", countryAr: "أستراليا", cityAr: "سيدني", latitude: -33.8688, longitude: 151.2093, timeZone: "Australia/Sydney" },
  { country: "Australia", city: "Melbourne", countryAr: "أستراليا", cityAr: "ملبورن", latitude: -37.8136, longitude: 144.9631, timeZone: "Australia/Melbourne" },
  { country: "Australia", city: "Brisbane", countryAr: "أستراليا", cityAr: "بريزبن", latitude: -27.4698, longitude: 153.0251, timeZone: "Australia/Brisbane" },
  { country: "India", city: "New Delhi", countryAr: "الهند", cityAr: "نيودلهي", latitude: 28.6139, longitude: 77.2090, timeZone: "Asia/Kolkata" },
  { country: "India", city: "Mumbai", countryAr: "الهند", cityAr: "مومباي", latitude: 19.0760, longitude: 72.8777, timeZone: "Asia/Kolkata" },
  { country: "India", city: "Hyderabad", countryAr: "الهند", cityAr: "حيدر آباد", latitude: 17.3850, longitude: 78.4867, timeZone: "Asia/Kolkata" },
  { country: "Pakistan", city: "Islamabad", countryAr: "باكستان", cityAr: "إسلام آباد", latitude: 33.6844, longitude: 73.0479, timeZone: "Asia/Karachi" },
  { country: "Pakistan", city: "Karachi", countryAr: "باكستان", cityAr: "كراتشي", latitude: 24.8607, longitude: 67.0011, timeZone: "Asia/Karachi" },
  { country: "Pakistan", city: "Lahore", countryAr: "باكستان", cityAr: "لاهور", latitude: 31.5204, longitude: 74.3587, timeZone: "Asia/Karachi" },
  { country: "Indonesia", city: "Jakarta", countryAr: "إندونيسيا", cityAr: "جاكرتا", latitude: -6.2088, longitude: 106.8456, timeZone: "Asia/Jakarta" },
  { country: "Indonesia", city: "Surabaya", countryAr: "إندونيسيا", cityAr: "سورابايا", latitude: -7.2575, longitude: 112.7521, timeZone: "Asia/Jakarta" },
  { country: "Malaysia", city: "Kuala Lumpur", countryAr: "ماليزيا", cityAr: "كوالالمبور", latitude: 3.1390, longitude: 101.6869, timeZone: "Asia/Kuala_Lumpur" },
  { country: "Malaysia", city: "George Town", countryAr: "ماليزيا", cityAr: "جورج تاون", latitude: 5.4141, longitude: 100.3288, timeZone: "Asia/Kuala_Lumpur" }
];

export function getPrayerLocation(country: string, city: string) {
  return prayerLocations.find((item) => item.country === country && item.city === city) || null;
}
